# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan Donnelly
email: ryanjdonnelly@gmail.com
description: >
  Ryan Donnelly is a developer and designer living in Ann Arbor. He really enjoys ultimate frisbee, music, and burritos.
author: rdonnelly
twitter:
  username: rdonnelly

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rdonnelly.com" # the base hostname & protocol for your site

twitter_username: rdonnelly
github_username:  rdonnelly

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
